### ISSUE TITLE
Pandas recipe doesn't work

### ISSUE THREAD

**Issue by tugsag** [kivy/python-for-android#2425]
### Versions

- Python: 3.7.5
- OS:  android
- Kivy: 2.0.0 master
- Cython: 0.29.21
- OpenJDK: 8

### Description

I'm trying to include pandas via the requirements in buildozer.spec file. The apk builds ok, but when I try to run it on my device, I get the error: ImportError: dlopen failed: cannot locate symbol  "_ZTVSt12length_error" referenced by "/data/data/org.test.matplotlib_testapp/files/app/_python_bundle/site-packages/pandas/_libs/window/aggregations.so"...

The curious thing is that this is supposedly addressed in the build recipe, but I still get the same error when trying to import pandas in my main.py file.

### buildozer.spec
This is what the requirements line looks like in the spec file
requirements = python3==3.7.5,kivy==2.0.0,hostpython3==3.7.9,numpy,pandas

Command:
```
buildozer android debug

```

### Logs

```
ImportError: dlopen failed: cannot locate symbol  "_ZTVSt12length_error" referenced by "/data/data/org.test.matplotlib_testapp/files/app/_python_bundle/site-packages/pandas/_libs/window/aggregations.so"..
```

**Comment by tshirtman** [comment]
I just forked my lottie demo repository to add pandas in the requirements, the package built and run on my phone, displaying a DataFrame.

https://github.com/tshirtman/p4a_pandas_test/actions/runs/579782702

you can grab the apk there and look at the code and configuration in the repository if it helps.

**Comment by RobertFlatt** [comment]
That comment in the recipe indicates `libandroid.so` was possibly not found.
That lib is part of the NDK.
No idea why that would be.

**Comment by tshirtman** [comment]
Apparently one needs to use p4a.branch=develop for pandas.

**Comment by HACKER-BYTE-HUE** [comment]
:smile:

**Comment by Revoluti0n** [comment]
I solved this using python lists instead of pandas module.. don't know if it's the best solution but its work now

**Comment by tugsag** [comment]
Yep, using develop branch fixed the issues. Thank you!

**Comment by tugsag** [comment]
It was working for a while, but using develop branch suddenly stopped working with the same dlopen failed issue. IDK why that would be

**Comment by yukhnovskiy** [comment]
@tugsag, have you solved a problem? Having same when running apk file built with kivy on Android 11 Sasmung S10e

**Comment by Revoluti0n** [comment]
@yukhnovskiy my app is working and stable so far using python native lists instead of pandas to manage data, same phone and also built with kivy

**Comment by yukhnovskiy** [comment]
@Revoluti0n thanks its possible way but not desired one, as a lot of refactoring is needed in my current project. Is there any workaround using pandas?

**Comment by yukhnovskiy** [comment]
btw here: https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/pandas/__init__.py
was some sollution, but seems it stopped working.

**Comment by yukhnovskiy** [comment]
Changing in recipe.py "need_stl_shared = True" solved issue for me. And pandas works fine.

**Comment by Revoluti0n** [comment]
@yukhnovskiy good job, thanks for sharing

**Comment by mzakharocsc** [comment]
For me, things worked fine on Android 10, Galaxy S10. On Android 11, Galaxy S21, I had the `_ZTVSt12length_error`. `need_stl_shared=True` was not enough. What did the trick is adding `self.stl_lib_name` to the following line in the pandas recipe:
```
        env['LDFLAGS'] += f' -landroid  -l{self.stl_lib_name}'

```

**Comment by tshirtman** [comment]
Feel free to open a pull request for the necessary changes :)

**Comment by AndreMiras** [comment]
Fixed via #2478 thanks for the pull request :muscle:

**Comment by alessandrofesti** [comment]
I keep having issues with pandas:
```
[INFO]:    Applying patch patches/fix-setup.patch
[INFO]:    -> running patch -t -d /home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/Pillow/armea...(and 189 more)
           working: 2 out of 3 hunks FAILED -- saving rejects to file setup.py.rej                                                                                                           Exception in thread background thread for pid 344403:
Traceback (most recent call last):
  File "/home/alessandro/anaconda3/envs/carty/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/alessandro/anaconda3/envs/carty/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/Pillow/armeabi-v7a__ndk_target_21/Pillow -p1 -i /home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/patches/fix-setup.patch

  STDOUT:
patching file setup.py
Hunk #1 succeeded at 120 (offset -5 lines).
Hunk #2 FAILED at 411.
patch unexpectedly ends in middle of line
Hunk #3 FAILED at 471.
2 out of 3 hunks FAILED -- saving rejects to file setup.py.rej


  STDERR:

[INFO]:    STDOUT:                                                                                                                                                                           
        patching file setup.py  
Hunk #1 succeeded at 120 (offset -5 lines).     
Hunk #2 FAILED at 411.  
patch unexpectedly ends in middle of line       
Hunk #3 FAILED at 471.  
2 out of 3 hunks FAILED -- saving rejects to file setup.py.rej
[INFO]:    STDERR:
        
Traceback (most recent call last):
  File "/home/alessandro/anaconda3/envs/carty/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/alessandro/anaconda3/envs/carty/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1294, in <module>
    main()
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 728, in __init__
    getattr(self, command)(args)
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 151, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 210, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 589, in build_recipes
    recipe.apply_patches(arch)
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 560, in apply_patches
    self.apply_patch(
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 263, in apply_patch
    shprint(sh.patch, "-t", "-d", build_dir, "-p1",
  File "/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 953, in next
    self.wait()
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/alessandro/.local/lib/python3.8/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/Pillow/armeabi-v7a__ndk_target_21/Pillow -p1 -i /home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/patches/fix-setup.patch

  STDOUT:
patching file setup.py
Hunk #1 succeeded at 120 (offset -5 lines).
Hunk #2 FAILED at 411.
patch unexpectedly ends in middle of line
Hunk #3 FAILED at 471.
2 out of 3 hunks FAILED -- saving rejects to file setup.py.rej


  STDERR:

# Command failed: /home/alessandro/anaconda3/envs/carty/bin/python -m pythonforandroid.toolchain create --dist_name=carty --bootstrap=sdl2 --requirements=python3==3.8.11,kivy==2.0.0,firebase_admin==5.0.2,cachetools,google-cloud,google-cloud-storage,android,requests==2.26.0,simplejson,openssl,Pillow==7.0.0,validate_email==1.3,urllib3==1.26.6,charset-normalizer,chardet,idna,certifi,requests_oauthlib,oauthlib,google-auth,pyasn1,pyasn1_modules,cryptography,google-api-python-client,openssl,httplib2,pyparsing,protobuf,google-api-core,cachecontrol,rsa,jwt,msgpack,pyyaml,autoconf,pandas==1.3.2,python-gettext,gettext,https://github.com/kivymd/KivyMD/archive/master.zip --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/alessandro/Scrivania/work/personal/carty/app/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/fester:@/tmp/.ICE-unix/22393,unix/fester:/tmp/.ICE-unix/22393'
#     QT_ACCESSIBILITY = '1'
#     SNAP_REVISION = '265'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     CONDA_EXE = '/home/alessandro/anaconda3/bin/conda'
#     _CE_M = ''
#     SNAP_REAL_HOME = '/home/alessandro'
#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
#     SNAP_USER_COMMON = '/home/alessandro/snap/pycharm-professional/common'
#     MANDATORY_PATH = '/usr/share/gconf/ubuntu.mandatory.path'
#     JAVA_HOME = '/usr/lib/jvm/java-8-openjdk-amd64/jre'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     TERM_SESSION_ID = '4cfe108c-d0f4-408e-a146-f691a7d5a4ec'
#     SNAP_INSTANCE_KEY = ''
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     SSH_AGENT_PID = '2891'
#     BAMF_DESKTOP_FILE_HINT = '/var/lib/snapd/desktop/applications/pycharm-professional_pycharm-professional.desktop'
#     GTK_MODULES = 'gail:atk-bridge'
#     PWD = '/home/alessandro/Scrivania/work/personal/carty/app'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     LOGNAME = 'alessandro'
#     XDG_SESSION_TYPE = 'x11'
#     CONDA_PREFIX = '/home/alessandro/anaconda3/envs/carty'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     DESKTOP_STARTUP_ID = 'gnome-shell/PyCharm Professional Edition/22407-0-fester_TIME12432746'
#     IM_CONFIG_CHECK_ENV = '1'
#     SNAP_CONTEXT = 'lX2-nmkYWB00VnjXujr4zArQfP_Hties__-CTm6CP7jz66fgFy1f'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     WINDOWPATH = '2'
#     HOME = '/home/alessandro'
#     USERNAME = 'alessandro'
#     IM_CONFIG_PHASE = '1'
#     LANG = 'it_IT.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     SNAP_ARCH = 'amd64'
#     SNAP_INSTANCE_NAME = 'pycharm-professional'
#     SNAP_USER_DATA = '/home/alessandro/snap/pycharm-professional/265'
#     CONDA_PROMPT_MODIFIER = '(carty) '
#     INVOCATION_ID = '487c480f9d78406c9c93c678322f2e97'
#     MANAGERPID = '2707'
#     SNAP_REEXEC = ''
#     GJS_DEBUG_OUTPUT = 'stderr'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     _CE_CONDA = ''
#     DEFAULTS_PATH = '/usr/share/gconf/ubuntu.default.path'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'alessandro'
#     SNAP = '/snap/pycharm-professional/265'
#     CONDA_SHLVL = '2'
#     SNAP_COMMON = '/var/snap/pycharm-professional/common'
#     SNAP_VERSION = '2021.3'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     SNAP_LIBRARY_PATH = '/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void'
#     SNAP_COOKIE = 'lX2-nmkYWB00VnjXujr4zArQfP_Hties__-CTm6CP7jz66fgFy1f'
#     QT_IM_MODULE = 'ibus'
#     SNAP_DATA = '/var/snap/pycharm-professional/265'
#     CONDA_PYTHON_EXE = '/home/alessandro/anaconda3/bin/python'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     CONDA_DEFAULT_ENV = 'carty'
#     SNAP_NAME = 'pycharm-professional'
#     JOURNAL_STREAM = '8:230638'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     PATH = '/home/alessandro/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/alessandro/.local/bin:/home/alessandro/anaconda3/envs/carty/bin:/home/alessandro/anaconda3/condabin:/home/alessandro/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     CONDA_PREFIX_1 = '/home/alessandro/anaconda3'
#     GIO_LAUNCHED_DESKTOP_FILE_PID = '24870'
#     GIO_LAUNCHED_DESKTOP_FILE = '/var/lib/snapd/desktop/applications/pycharm-professional_pycharm-professional.desktop'
#     _ = '/home/alessandro/.local/bin/buildozer'
#     OLDPWD = '/home/alessandro/Scrivania/work/personal/carty'
#     PACKAGES_PATH = '/home/alessandro/.buildozer/android/packages'
#     ANDROIDSDK = '/home/alessandro/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/alessandro/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```
Below my spec  file
```
# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts =

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.2

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3==3.8.11,kivy==2.0.0,firebase_admin==5.0.2,cachetools,google-cloud,google-cloud-storage,android,requests==2.26.0,simplejson,openssl,Pillow==7.0.0,validate_email==1.3,urllib3==1.26.6,charset-normalizer,chardet,idna,certifi,requests_oauthlib,oauthlib,google-auth,pyasn1,pyasn1_modules,cryptography,google-api-python-client,openssl,httplib2,pyparsing,protobuf,google-api-core,cachecontrol,rsa,jwt,msgpack,pyyaml,autoconf,pandas==1.3.2,python-gettext,gettext,https://github.com/kivymd/KivyMD/archive/master.zip

# (str) Custom source folders for requirements
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = all

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 2.0

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET,CHANGE_WIFI_MULTICAST_STATE,ACCESS_NETWORK_STATE,ACCESS_WIFI_STATE

# (int) Target Android API, should be as high as possible.
android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master (maybe to change to develop)
p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

**Comment by marcets** [comment]
I think the recipes is for pandas 1.0.3 (see the pull request)

**Comment by alessandrofesti** [comment]
Thanks!

**Comment by magowiz** [comment]
I still encounter issues for this, I tried to follow suggestions provided in this bug report comments but at the moment I cannot make my project work on android with pandas: 
I'm talking about @yukhnovskiy, @mzakharocsc comments and reccomendation of @tshirtman to use develop branch of p4a, I was able to check the pandas recipe in develop contains already the instructions suggested, Anyway I've got this error when running on my phone:
```
08-16 15:30:26.767 22874 22921 I python  :  ImportError: C extension: dlopen failed: TLS symbol "_ZZN8gwp_asan15getThreadLocalsEvE6Locals" in dlopened "/data/user/0/net.magowiz.travel_lint/files/app/_python_bundle/site-packages/pandas/_libs/tslibs/conversion.so" referenced from "/data/user/0/net.magowiz.travel_lint/files/app/_python_bundle/site-packages/pandas/_libs/tslibs/conversion.so" using IE access model not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
``` 
I don't know if it is the same problem or a related one, I also pinned pandas version to 1.0.3 the one indicated by recipe, to be sure I was using a fixed one, here it is mine buildozer.spec file:
```
[app]
title = Travel Lint
package.name = travel_lint
package.domain = net.magowiz
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,md,rst,txt,json,ini
source.exclude_dirs = tests, bin, .buildozer, .pytest_cache, ~, htmlcov, kivymd_example,
                      features
source.exclude_patterns = *.spec, .coverage*, pylintrc, *.sh, requirements.txt,
                          pytest.ini, token.json
version.regex = __version__ = ['"](.*)['"]
version.filename = main.py
requirements = libbz2, hostpython3==3.9.9, python3==3.9.9, kivy==2.1.0, kivymd==0.104.2, Pillow, pygments, m2rr,
               docutils==0.18.1, mistune==0.8.4, sdl2_ttf==2.0.15, httplib2, pyparsing,
               uritemplate, google-api-python-client,google, six==1.12.0,
               google-auth-httplib2, google-auth-oauthlib, google-api-core,
               google-auth, requests, urllib3, chardet, certifi, idna,
               cachetools, pyasn1, pyasn1_modules, rsa, requests_oauthlib,
               oauthlib, dropbox, stone, country_list, geopy, forex_python, simplejson,
               countryinfo, pyowm, geojson, attr, O365, stringcase, tzlocal,
               pytz_deprecation_shim, backports-zoneinfo, pytz, dateutil, beautifulsoup4,
               currency_converter_with_rate, pandas==1.0.3
presplash.filename = logo.png
icon.filename = logo.png
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = INTERNET, STORAGE
android.accept_sdk_license = True
android.arch = armeabi-v7a
p4a.branch=develop
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0
[buildozer]
log_level = 2
warn_on_root = 1
```

**Comment by misl6** [comment]
Hi @magowiz !

I've just merged a fix on `develop` that may fix your issue. (Please be sure to do a clean build)

Feel free to open a new issue if you still encounter any issues.

**Comment by magowiz** [comment]
Hi @misl6,
I can confirm that now, after your fix, I used develop branch of p4a and pandas error goes away, thank you.
I can see now a module not found error but it is my fault since I forgot to put that module in buildozer.spec requirements :-)
