### ISSUE TITLE
trouble compiling some modules with revamp

### ISSUE THREAD

**Issue by radiodee1** [kivy/python-for-android#473]
https://gist.github.com/806e413b1da4dfa7ac58

as shown in this gist, pygame does not work. I am using kivy 1.8.0, python-for-android 0.3, and ubuntu 15.04 on a desktop computer. Originally when I first posted this problem on the Google Group, I was using cython 0.23.3. Since then I have tried using cython 0.21.1 but with the same results.
##

**Comment by inclement** [comment]
Thanks for reporting this here, but it seems your link doesn't work.

**Comment by inclement** [comment]
Oh, and have you tried the sdl2 backend? It would be worthwhile to check if you can just create a dist with this, to check if it's something about pygame in particular.

**Comment by radiodee1** [comment]
https://gist.github.com/radiodee1/806e413b1da4dfa7ac58

**Comment by radiodee1** [comment]
here's a sdl2 backend attempt

https://gist.github.com/radiodee1/948c1df527721ca4bdd3

**Comment by inclement** [comment]
[DEBUG]:   running touch /home/dave/.local/share/python-for-android/build/other_builds/pyjnius-sdl2/armeabi/pyjnius/.patched
    [INFO]:    Prebuilding kivy for armeabi
    [INFO]:    kivy has no prebuild_armeabi, skipping
    [INFO]:    Applying patch android_sdl2_compat.patch
    
The failure to apply this patch is because I removed it and added the changes in the kivy master branch. Could you make sure your p4a is up to date from the python-for-android master branch and try again?

**Comment by radiodee1** [comment]
thanks. If I run the following 

    ~/.local/bin/p4a clean_builds

    git clone  https://github.com/kivy/python-for-android.git 
    cd python-for-android
    python setup.py install --user
    ~/.local/bin/python-for-android create --debug --dist_name=AwesomeCNN --bootstrap=pygame --requirements=pyjnius,kivy

I get:
https://gist.github.com/radiodee1/3c58e8607b131d419287

**Comment by inclement** [comment]
Could you do it with sdl2 again? I'd like to check if that can get all the way to the end

**Comment by radiodee1** [comment]
here's the output if I change the --bootstrap to sdl2. Honestly I don't know much about sdl2 or how the p4a bootstrap works. Also, I don't know exactly how to make sure that the build is starting over from scratch. I have been deleting the folder '~/.local/share/python-for-android' and the 'python-for-android' folder that was created by the 'git clone' command. I also execute 'p4a clean_builds'. Is there something else I should or should not do?

    ~/.local/bin/python-for-android create --debug --dist_name=AwesomeCNN --bootstrap=sdl2 --requirements=pyjnius,kivy

Here is the link to the gist.

https://gist.github.com/radiodee1/3ab09594de84d4019697

**Comment by inclement** [comment]
That's the same problem as before, are you sure you replaced p4a properly?

It's no problem to not know about sdl2, I just want to see if it compiles or hits a similar error.

**Comment by radiodee1** [comment]
https://gist.github.com/radiodee1/437ada8a3cf8a8572527

I did make sure that p4a was installed over again.

**Comment by radiodee1** [comment]
At the top of this issue I said I changed the cython version from 0.23.3 to 0.21.1. Just now I found I could not update the version of kivy on my desktop to 1.9.0.  After examining cython I found that v0.23.3 was partially uninstalled. I thought this would prove to be the underlying problem. I fixed cython so that it was 0.21.1 and installed kivy 1.9.0 successfully. The big let down is that this did NOT change my p4a problem. I tried with the sdl2 backend and the pygame backend but neither made it all the way to the end of the build. Both show the same output as above.

**Comment by inclement** [comment]
The error in the sdl2 log is with `[1m[INFO][0m: Applying patch android_sdl2_compat.patch`. This patch is no longer applied, you can see at https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/kivy/__init__.py that the prebuild function no longer exists.

For this reason, I still don't think your p4a is up to date with the master branch.

**Comment by radiodee1** [comment]
this:

        git clone -b master https://github.com/kivy/python-for-android.git 

and this:

        git clone  https://github.com/kivy/python-for-android.git 

don't seem to produce the right version. what am I doing wrong? Is there something simple I'm not doing in the way of downloading?

**Comment by radiodee1** [comment]
I have downloaded the p4a git clone again, and have run the following command to produce output that does not include the android_sdl2_compat.patch, but still doesn't work. This gist uses the sdl2 backend

https://gist.github.com/radiodee1/4e3a97ccbeefaf9c6e66

The command line is:

    ~/.local/bin/python-for-android create --debug --dist_name=AwesomeCNN --bootstrap=sdl2 --requirements=pyjnius,kivy

this is not the longish output that would have come from executing the command after "p4a clean_builds".

**Comment by radiodee1** [comment]
disregard my last post. I ran the command again after "p4a clean_builds". the longer output does show the patch, and I cannot figure how to download the newest p4a sources. I don't know what the problem is. I looked in the cloned 'python-for-android' folder, in the kivy recipe, and there's no android_sdl2_compat.patch. I don't know how it gets in there every time I run p4a.

**Comment by radiodee1** [comment]
the patch 'android_sdl2_compat.patch' is in the recipe 'kivysdl2python3' and from there it is appearing in my listings. It is not from the 'kivy' recipe, and it is still part of p4a sources at this time. I don't know why the kivysdl2python3 recipe is used. I thought I was using python 2.7 or something like that. Sorry for all the misguided posts about getting the most recent version of p4a.

**Comment by radiodee1** [comment]
I tried this line, hoping that kivysdl2python3 would not be called:

    ~/.local/bin/python-for-android create --debug --dist_name=AwesomeCNN --bootstrap=sdl2 --requirements=python2,sdl2,kivy

but it is. I tried this line:

    ~/.local/bin/python-for-android create --debug --dist_name=AwesomeCNN --bootstrap=sdl2 --requirements=python2,sdl2

and the build finished. If I add kivy to the requirements it calls pyjnius as a dependnecy and the build fails. It seems that if I put anything as a requirement it fails. The output always has kivysdl2python3 in it. If I use the pygame backend and remove sdl2 from the dependencies it fails.

Here's the output with sdl2 backend and no requirements that succeeded, but still has kivysdl2python3 in it:

https://gist.github.com/radiodee1/49c0203080a9a477dda2

**Comment by radiodee1** [comment]
can anyone suggest for me how to use the python bootstrap?!!

**Comment by inclement** [comment]
I'm afraid I still don't know what could be wrong here, based on the previous discussion - I don't want to ignore this, but I'm out of ideas :/

**Comment by inclement** [comment]
Closing as stale and probably fixed in master.
