### ISSUE TITLE
sqlite3 recipe not working with new toolchain

### ISSUE THREAD

**Issue by Benedikt1992** [kivy/python-for-android#977]
https://github.com/kivy/buildozer/issues/450

**Comment by Benedikt1992** [comment]
If you already know what would be necessary to build the sqlite module. I could at least try to implement it

**Comment by WillDHB** [comment]
Have you whitelisted sqlite3?  I believe I've actually used sqlite3 with the new toolchain.

**Comment by Benedikt1992** [comment]
@WillDHB What do you mean by 'whitelist'?

**Comment by WillDHB** [comment]
Some stuff is "blacklisted" by default to save on space.  sqlite3 is one such module.  You can remove it from the blacklist or you can whitelist it.  If you're using buildozer, try poking around in your spec file.  If you're using p4a directly, then investigate the blacklist/whitelist options: http://python-for-android.readthedocs.io/en/latest/buildoptions/?highlight=blacklist

**Comment by Benedikt1992** [comment]
I've tried to add `android.p4a_whitelist = sqlite3` to `buildozer.spec`

Still its not working. I've also tried all combinations of requirements and whitelist. 
 * `sqlite3` nowhere specified
 * `sqlite3` just as requirement
 * `sqlite3` just on the whitelist
 * `sqlite3` as requirement and on the whitelist

**Comment by inclement** [comment]
You shouldn't need to whitelist sqlite3.

**Comment by WillDHB** [comment]
I'm not sure what to say to the fact that you shouldn't need to whitelist sqlite3.  When I first added sqlite3 to my project, it wouldn't build until I added it to my buildozer.spec's whitelist:

`android.p4a_whitelist = encodings/cp1252.pyo,sqlite3/*,lib-dynload/_sqlite3.so`

(That first pyo isn't related).
I have it as a requirement as well, though I'm not sure if that's necessary.

I chose these patterns by pulling up p4a's sdl2 blacklist.txt and searching for sqlite3, which led to this paragraph:
```
#>sqlite3
# conditionnal include depending if some recipes are included or not.
sqlite3/*
lib-dynload/_sqlite3.so
#<sqlite3
```

Perhaps this has changed since I set up my project.

**Comment by inclement** [comment]
@WillDHB Telling me I'm mistaken is a fine response.

It looks like this behaviour is a new toolchain bug - in the old toolchain the sqlite3 recipe deleted the sqlite3 section from the blacklist, but this behaviour was missing in the new one. I've pushed a fix (https://github.com/kivy/python-for-android/pull/1000) that should hopefully resolve this.

Thanks for the report.

**Comment by Benedikt1992** [comment]
After `buildozer android_new clean` it unfortunately still fails to build. Compiler says `cannot create executables`. The Message basically hasn't changed.

**Comment by inclement** [comment]
Oops, sorry, I didn't mean to actually close this issue.

**Comment by germn** [comment]
@Benedikt1992 hello, I've just successfully build apk with sqlite3 on Ubuntu 16.04. I also got error `cannot create executables`, which was solved for me after replacing `hostpython2` with `python2` in requirements (saw solution [here](https://github.com/kivy/buildozer/issues/395#issuecomment-279398881)). Full requirements:

`requirements = python2, android, kivy, sqlite3, sqlalchemy`

You may try install latest p4a/buildozer, clean your `.buildozer` folder and try to build apk again.

**Comment by Benedikt1992** [comment]
@germn This seems to work. At least the build process does not break.

**Comment by inclement** [comment]
Did you have any more problems of this nature after those most recent comments? If not, I think this is a manifestation of a different issue about how requirements are chosen.

**Comment by Benedikt1992** [comment]
No didn't recognize more issues of this kind

**Comment by inclement** [comment]
sqlite3 is currently working fine.
